<MyToggleButton>:
    style: 'outlined'
    radius: 2
    MDButtonText
        text: root.text

<SpeedControl>:
    orientation: 'vertical'
    spacing: '12dp'
    adaptive_height: True

    MDLabel:
        text: f'Speed: {root.speed}'
        font_style: 'Title'
        pos_hint: {'center_x': .5, 'center_y': .5}
        adaptive_height: True

    MDBoxLayout:
        id: speed_box
        adaptive_height: True


